// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Yayathon 2026 bireysel başvuruları açıldı. Takımlar organizasyon komitesi tarafından oluşturulacaktır.\n\nBaşvurular bireysel olarak alınır. Hazır takım başvuruları kabul edilmez.\nKatılımcı profilleri; disiplin çeşitliliği ve denge kriterleri gözetilerek 10×10 modeliyle hibrit takımlara dağıtılır.\nBaşvuru adımlarını tamamladıktan sonra gönderim ekranında “Başvuruyu gönder” ile işlemi bitirebilirsiniz.",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Başvurular Açıldı"
                        },
                        new
                        {
                            Id = 2,
                            Content = "5 Haziran saha keşfi programının ana akışı ve buluşma noktaları duyuruldu.\n\nSaha keşfi, İzmit kent merkezi odaklı tramvay turu ve rehberli yürüyüşleri kapsar.\nKatılımcıların rahat yürüyüş ayakkabısı ve hava koşullarına uygun ekipmanla gelmeleri önerilir.\nDetaylı program “Takvim” sayfasında güncellenecektir.",
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Saha Keşfi Programı Duyurusu"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lojistik ve etkinlik kuralları hakkında yeni sorular eklendi, yanıtlar güncellendi.\n\nKendi bilgisayarınızı getirmeniz beklenir; sınırlı sayıda yazılım/donanım desteği sağlanabilir.\nEtkinlik günü iaşe organizasyon tarafından karşılanacaktır.\nYeni sorular için “SSS” sayfasını ziyaret edebilirsiniz.",
                            CreatedAt = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "SSS Güncellemesi"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Hackathon günü mentorluk slotları ve branş bazlı masa düzeni duyuruldu.\n\nMimarlık, ulaşım planlama ve yazılım mentorları için ayrı istişare alanları belirlendi.\nSlotlar, kayıt sonrası katılımcı panelinden görüntülenebilecek.",
                            CreatedAt = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Mentor Görüşme Takvimi"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Bireysel başvurular 25 Mayıs 2026 saat 23:59’a kadar alınmaya devam edecek.\n\nBaşvuru formunda zorunlu alanların tamamlandığından emin olun.\nOnay e-postası gönderiminde gecikme yaşanmaması için iletişim bilgilerinizi kontrol edin.",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Son Başvuru Tarihi Hatırlatması"
                        },
                        new
                        {
                            Id = 6,
                            Content = "İzmit ve Darıca için güncel pafta özetleri ve yaya güvenliği istatistikleri pakete eklendi.\n\nİndirilebilir kaynaklar sayfasından yeni sürüme erişebilirsiniz (yayınlandığında).\nÖnceki çalışmalarınızı yeni katmanlarla uyumlu hale getirmeniz önerilir.",
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Teknik Veri Paketi Güncellemesi"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Luxor Garden Park Hotel çevresi toplu taşıma hatları ve misafir otopark yönlendirmesi paylaşıldı.\n\nİzmit merkezden tramvay ve otobüs bağlantıları için özet harita eklendi.\nEtkinlik günü vale ve alternatif park alanları organizasyon tarafından iletilecek.",
                            CreatedAt = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Ulaşım ve Otopark Bilgisi"
                        },
                        new
                        {
                            Id = 8,
                            Content = "5 dakikalık sunumda beklenen başlıklar ve yedek materyal (poster / kısa video) kuralları netleştirildi.\n\nSunum şablonu indirilebilir kaynaklar bölümünde yer alacaktır.\nTeknik aksaklıklar için USB yedek ve PDF çıktı getirmeniz tavsiye edilir.",
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Jüri Sunum Formatı"
                        },
                        new
                        {
                            Id = 9,
                            Content = "5 Haziran saha programı için hava durumuna uygun kıyafet ve rahat ayakkabı zorunluluğu hatırlatması.\n\nUzun süre ayakta ve yürüyüş içeren programda su ve şapka bulundurmanız önerilir.\nÖzel sağlık durumunuzu kayıt sırasında bildirmeniz önemlidir.",
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Title = "Saha Keşfi Hava ve Ekipman"
                        });
                });

            modelBuilder.Entity("Api.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$Ki2HmjBB5QVx56TWNY348eWsdMsdo4Ojn0Xd4pY5G/woTEa/pXhDG",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
